### ISSUE TITLE
index out of bounds: the len is 30 but the index is 30

### ISSUE THREAD

**Issue by QuarkContainer** [rcore-os/buddy_system_allocator#14]
There is a bug in lib.rs between L158 to L 178.

Provide the ORDER is 30. If the current_class is 29, i.e. the last index, the L174 will get error "Index out of bounds".

            while current_class < self.free_list.len() {
                let buddy = current_ptr ^ (1 << current_class);
                let mut flag = false;
                for block in self.free_list[current_class].iter_mut() {
                    if block.value() as usize == buddy {
                        block.pop();
                        flag = true;
                        break;
                    }
                }

                // Free buddy found
                if flag {
                    self.free_list[current_class].pop();
                    current_ptr = min(current_ptr, buddy);
                    current_class += 1;
                    self.free_list[current_class].push(current_ptr as *mut usize);
                } else {
                    break;
                }
            }

**Comment by jiegec** [comment]
Can you provide an code example where this bug can occur? In the design, 30 essentially sets a limit for the total memory.

**Comment by QuarkContainer** [comment]
I am using the buddy allocator in https://github.com/QuarkContainer/Quark/commits/main/qkernel/src/memmgr/list_allocator.rs


In my scenario, the total memory is 4GB or 8GB. I think it will reach ORDER 32 or 33. So my workaround is to set ORDER to 33 and the issue is solved now.




________________________________
