### ISSUE TITLE
using the crate of version "0.9" meeting the error about using unstabele api

### ISSUE THREAD

**Issue by kyrosle** [rcore-os/buddy_system_allocator#25]
When i learning the `rcore` in windows platform, i use this crate with version `0.9`, instead of the version in tutorial is `0.6`. I meet the error 
![image](https://user-images.githubusercontent.com/74538854/229987168-4275f740-a508-4cbd-bf67-addeb5019b8a.png)
and here is the code lab in this commit: 
https://github.com/kyrosle/OS/tree/ccb88e0819c230fa53df1cc2993f05c5eab9fcd3

Only using `0.9` will cause this error, but `0.8` seem all right.

**Comment by wangrunji0408** [comment]
[array::from_fn](https://doc.rust-lang.org/stable/std/array/fn.from_fn.html) was not stabled until Rust 1.63.0 (2022-08-11). You may update toolchain for your project, or add the `#![feature(...)]`, or keep this crate at v0.8. It's reasonable for a crate to use new APIs in a new version.
